name: 'my_databricks_project'
version: '1.0.0'
config-version: 2

profile: 'my_databricks_project'

model-paths: ["models"]
macro-paths: ["macros"]


target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_databricks_project:
    +catalog: "hive_metastore"  # required for Unity Catalog

    clean:
      +schema: "clean"
      +materialized: view

    aggregate:
      +schema: "aggregate"
      +materialized: table

    analytics:
      +schema: "analytics"
      +materialized: table
